<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <tr>
        <td href ="PRODUK.PHP"> menu produk</td>
        <td href ="PEMBELIAN.PHP"> menu pembelian </td>
        
</tr>

<tr>
    <td> welocme

</td>

</tr>




</body>
</html>